project_id = "fcrdwjukkchdibmpyjkg"

[functions.toggle-follow]
verify_jwt = false

[functions.mobile-auth]
verify_jwt = false

[functions.messaging]
verify_jwt = false

[functions.manage-community]
verify_jwt = false

[functions.create-business]
verify_jwt = false

[functions.create-comment]
verify_jwt = false

[functions.create-post]
verify_jwt = false

[functions.manage-business]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.toggle-like]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.upload-avatar]
verify_jwt = false

[functions.verify-email]
verify_jwt = false
